name: regbot-installer
author: regclient
description: 'Docker registry client'
branding:
  icon: 'layers'
  color: 'blue'
inputs:
  release:
    description: 'version to install'
    required: false
    default: 'latest'
  install-dir:
    description: 'where to install the binary'
    required: false
runs:
  using: 'composite'
  steps:
    - env:
        RELEASE: ${{ inputs.release }}
        INSTALL_DIR: ${{ inputs.install-dir }}
        INSTALL_CMD: regbot
      shell: bash
      run: |
        #!/bin/bash
        set -ex
        shopt -s expand_aliases
        if [ -z "$NO_COLOR" ]; then
          alias log_info="echo -e \"\033[1;32mINFO\033[0m:\""
          alias log_error="echo -e \"\033[1;31mERROR\033[0m:\""
        else
          alias log_info="echo \"INFO:\""
          alias log_error="echo \"ERROR:\""
        fi
        if [ -z "${INSTALL_DIR}" ]; then
          INSTALL_DIR="${HOME}/.regbot/bin"
        fi
        log_info "installing to ${INSTALL_DIR}"
        mkdir -p "${INSTALL_DIR}"
        url_base="https://github.com/regclient/regclient"
        url_ext=""
        if [ "${{ runner.os }}" = "Windows" ]; then
          url_ext=".exe"
        fi
        if [ "${RELEASE}" = "main" ]; then
          log_info "Installing using go install from main..."
          go install github.com/regclient/regclient/cmd/${INSTALL_CMD}@main
          GOPATH=$(go env GOPATH)
          ln -s "$GOPATH/bin/${INSTALL_CMD}${url_ext}" "${INSTALL_DIR}/${INSTALL_CMD}${url_ext}"
          echo "${INSTALL_DIR}" >> $GITHUB_PATH
          log_info "install complete"
          exit 0
        elif [ "${RELEASE}" = "latest" ]; then
          url_release="releases/latest/download"
        else
          url_release="releases/download/${RELEASE}"
        fi
        case "${{ runner.os }}-${{ runner.arch }}" in
          Linux-X64)   url_platform="linux-amd64" ;;
          Linux-ARM64) url_platform="linux-arm64" ;;
          macOS-X64)   url_platform="darwin-amd64" ;;
          macOS-ARM64) url_platform="darwin-arm64" ;;
          Windows-X64) url_platform="windows-amd64" ;;
          *)
            log_error "architecture not supported: ${{ runner.os }}-${{ runner.arch }}"
            exit 1
            ;;
        esac
        curl -sL "${url_base}/${url_release}/${INSTALL_CMD}-${url_platform}${url_ext}" -o "${INSTALL_DIR}/${INSTALL_CMD}${url_ext}"
        chmod +x "${INSTALL_DIR}/${INSTALL_CMD}${url_ext}"
        if [ -x "$(command -v cosign)" ]; then
          log_info "verifying cosign signature"
          curl -L "${url_base}/${url_release}/metadata.tgz" >metadata.tgz
          # first try to verify the bundle
          if tar -xzf metadata.tgz "${INSTALL_CMD}-${url_platform}.sigstore.json"; then
            cosign verify-blob \
              --certificate-oidc-issuer https://token.actions.githubusercontent.com \
              --certificate-identity-regexp https://github.com/regclient/regclient/.github/workflows/ \
              --bundle "${INSTALL_CMD}-${url_platform}.sigstore.json" \
              "${INSTALL_DIR}/${INSTALL_CMD}${url_ext}"
            rm metadata.tgz "${INSTALL_CMD}-${url_platform}.sigstore.json"
          # else try to verify the individual pem/sig
          elif tar -xzf metadata.tgz "${INSTALL_CMD}-${url_platform}.pem" "${INSTALL_CMD}-${url_platform}.sig"; then
            cosign verify-blob \
              --certificate-oidc-issuer https://token.actions.githubusercontent.com \
              --certificate-identity-regexp https://github.com/regclient/regclient/.github/workflows/ \
              --certificate "${INSTALL_CMD}-${url_platform}.pem" \
              --signature "${INSTALL_CMD}-${url_platform}.sig" \
              "${INSTALL_DIR}/${INSTALL_CMD}${url_ext}"
            rm metadata.tgz "${INSTALL_CMD}-${url_platform}.pem" "${INSTALL_CMD}-${url_platform}.sig"
          else
            log_error "metadata not available for cosign verification"
            rm metadata.tgz
          fi
        fi
        echo "${INSTALL_DIR}" >> $GITHUB_PATH
        log_info "install complete"
    - if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      env:
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: |
        $installdir = "$env:INSTALL_DIR"
        if (!$installdir) {
          $installdir = Join-Path $HOME '.regbot\bin'
        }
        echo "Adding to path $installdir"
        echo "$installdir" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
