name: regsync-installer
author: regclient
description: 'Docker registry client'
branding:
  icon: 'layers'
  color: 'blue'
inputs:
  release:
    description: 'version to install'
    required: false
    default: 'latest'
  install-dir:
    description: 'where to install the binary'
    required: false
    default: '$HOME/.regsync/bin'
runs:
  using: 'composite'
  steps:
    - uses: ./cmd-installer
      with:
        install-cmd: regsync
        release: ${{ inputs.release }}
        install-dir: ${{ inputs.install-dir }}
