name: regctl-login
author: regclient
description: 'regctl Registry Login'
branding:
  icon: 'layers'
  color: 'blue'
inputs:
  registry:
    description: registry server to login
    required: false
    default: ghcr.io
  username:
    description: username for authentication
    required: false
    default: ${{ github.actor }}
  password:
    description: password to login with
    required: false
    default: ${{ github.token }}
  options:
    description: options for regctl registry login, e.g. --skip-check
    required: false
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
      run: |
        echo "::add-mask::${PASSWORD}"
        echo "${PASSWORD}" | regctl registry login "${REGISTRY}" -u "${USERNAME}" --pass-stdin ${{ inputs.options }}
