# Copyright the regclient contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc*'

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-tags: true

    - name: Gather release details
      if: startsWith( github.ref, 'refs/tags/v' ) && github.repository_owner == 'regclient'
      id: release_details
      env:
        RELEASE_FILE: RELEASE.md
        TMP_FILE: /tmp/release.md
        RELEASE_PREFIX: "## Release "
      run: |
        # parse file to get the tag, and write current release notes to a temp file
        awk "/^${RELEASE_PREFIX}/{if(++c>1)exit} c==1" <"${RELEASE_FILE}" >"${TMP_FILE}"
        VERSION=${GITHUB_REF#refs/tags/}
        VALID_RELEASE=false
        if [ -f "${TMP_FILE}" ] && grep -q "Release $VERSION" "${TMP_FILE}"; then
          VALID_RELEASE=true
        fi
        if [[ $VERSION =~ [0-9\.]+-.+$ ]]; then
          PRERELEASE=true
        else
          PRERELEASE=false
        fi
        echo "pre_release=${PRERELEASE}" >>$GITHUB_OUTPUT
        echo "release_file=${TMP_FILE}" >>$GITHUB_OUTPUT
        echo "valid=${VALID_RELEASE}" >>$GITHUB_OUTPUT
        echo "version=${VERSION}" >>$GITHUB_OUTPUT

    - name: Create release
      if: steps.release_details.outputs.valid == 'true' && matrix.gover == env.RELEASE_GO_VER
      id: release_create
      uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_details.outputs.version }}
        body_path: ${{ steps.release_details.outputs.release_file }}
        draft: false
        prerelease: ${{ steps.release_details.outputs.pre_release }}
        files: ./artifacts/*
